<script setup lang="ts">
const props = defineProps<{ status?: string }>()

const labels: Record<string, string> = {
  PLANNING: '筹备中',
  IN_PROGRESS: '进行中',
  CLIENT_REVIEW: '待客户审核',
  PUBLISHING: '发布中',
  MONITORING: '监测中',
  COMPLETED: '已完成',
  ARCHIVED: '已归档',
  SUBMITTED: '已提交',
  PENDING_SUBMISSION: '待提交',
  PENDING_ACCEPTANCE: '待项目确认',
  PENDING_INFO: '待补充资料',
  ACCEPTED: '已接单',
  EXECUTING: '执行中',
  // Assignment is an internal staffing operation. Customers only need to know
  // that the platform is arranging the next executable step.
  PENDING_ASSIGNMENT: '待平台安排',
  PENDING_EXECUTION: '待执行',
  NEEDS_INFO: '需补充',
  EXCEPTION: '异常',
  CLIENT_ACCEPTED: '客户已验收',
  AWAITING_CLIENT_ACCEPTANCE: '待客户验收',
  CLIENT_RETURNED: '客户退回',
  CLIENT_APPROVED: '客户确认',
  APPROVED: '已确认',
  VERIFIED: '已核验',
  ACTIVE: '可用',
  INACTIVE: '已停用',
  SUPERSEDED: '已被替代',
  NEW: '待联系',
  PENDING: '待处理',
  CONTACTED: '已联系',
  CLOSED: '已关闭',
  PENDING_SCOPE: '待确认范围',
  BLOCKED: '受阻',
  PAID: '已结清',
  CONFIRMED: '已确认',
  VOIDED: '已作废',
  WAITING_CONFIRMATION: '待确认',
  TASK_CREATED: '已生成任务',
  CANCELLED: '已取消',
  DRAFT: '草稿',
  PUBLISHED: '已发布',
  SUSPENDED: '已停用',
  CANDIDATE: '候选',
  READY_TO_INVITE: '待邀约确认',
  WAITING_MATCH: '待匹配',
  OFFERED: '待接单',
  PARTIALLY_ACCEPTED: '部分接单',
  REVIEW_REQUIRED: '待复核',
  PENDING_VERIFICATION: '待核验',
  MANUAL_REVIEW: '待项目核验',
  LINK_AVAILABLE: '成果待核验',
  REPORTED: '已回填',
  EXPIRED: '已到期',
  RELEASED: '已释放',
  AVAILABLE: '可用',
  SUCCESS: '成功',
  FAILED: '失败',
  INVITED: '已发出邀请',
  RESPONDED: '已回复',
  DECLINED: '婉拒',
  ATTENDING: '确认到场',
  NOT_PROCEEDING: '暂不推进',
}

const tone: Record<string, string> = {
  COMPLETED: 'success',
  CLIENT_ACCEPTED: 'success',
  APPROVED: 'success',
  VERIFIED: 'success',
  ACTIVE: 'success',
  CONTACTED: 'success',
  CLOSED: 'neutral',
  ACCEPTED: 'success',
  SUCCESS: 'success',
  PAID: 'success',
  CONFIRMED: 'success',
  EXCEPTION: 'danger',
  BLOCKED: 'danger',
  CLIENT_RETURNED: 'danger',
  CANCELLED: 'danger',
  VOIDED: 'danger',
  SUSPENDED: 'danger',
  FAILED: 'danger',
  DECLINED: 'danger',
  NOT_PROCEEDING: 'danger',
  CLIENT_REVIEW: 'warning',
  AWAITING_CLIENT_ACCEPTANCE: 'warning',
  NEEDS_INFO: 'warning',
  PENDING: 'warning',
  NEW: 'warning',
  PENDING_SCOPE: 'warning',
  PENDING_ASSIGNMENT: 'warning',
  PENDING_SUBMISSION: 'warning',
  PENDING_ACCEPTANCE: 'warning',
  PENDING_INFO: 'warning',
  WAITING_CONFIRMATION: 'warning',
  WAITING_MATCH: 'warning',
  OFFERED: 'warning',
  PARTIALLY_ACCEPTED: 'info',
  REVIEW_REQUIRED: 'warning',
  PENDING_VERIFICATION: 'warning',
  MANUAL_REVIEW: 'warning',
  LINK_AVAILABLE: 'warning',
  IN_PROGRESS: 'info',
  EXECUTING: 'info',
  PUBLISHING: 'info',
  MONITORING: 'info',
  PENDING_EXECUTION: 'info',
  TASK_CREATED: 'info',
  INVITED: 'info',
  RESPONDED: 'info',
  ATTENDING: 'success',
  CANDIDATE: 'warning',
  READY_TO_INVITE: 'warning',
}
</script>

<template>
  <span class="status-tag" :class="`status-${tone[props.status || ''] || 'neutral'}`">{{
    labels[props.status || ''] || '状态待更新'
  }}</span>
</template>
